[project]
name = "flipframe"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "aryannpanwarr", email = "aryannpanwarr@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "anthropic>=1.5.0",
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
flipframe = "flipframe:main"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"
